### ISSUE TITLE
a.getTime is not a function

### ISSUE THREAD

**Issue by jmichaelterenin** [kevinkhill/lavacharts#230] opened 2018-01-21 11:48 UTC
#### Issue
I'm getting the error: a.getTime is not a function when trying to set the horizontal label values to \DateTime objects. I assume this is the way to do this?

#### Controller Code (chart creation code)
```
<div id="spreadgraph"><div id="google-visualization-errors-all-1" style="display: block; padding-top: 2px;"><div id="google-visualization-errors-0" style="font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 0.8em; line-height: normal; font-family: arial, sans-serif; margin-bottom: 5px;"><span style="background-color: rgb(192, 0, 0); color: white; padding: 2px;">a.getTime is not a function<span style="font-size: 1.1em; font-weight: bold; cursor: pointer; padding-left: 10px; color: black; text-align: right; vertical-align: top;">×</span></span></div></div><div style="position: relative;"><div dir="ltr" style="position: relative; width: 1200px; height: 800px;"><div style="position: absolute; left: 0px; top: 0px; width: 100%; height: 100%;"></div></div><div aria-hidden="true" style="display: none; position: absolute; top: 810px; left: 1210px; white-space: nowrap; font-family: Arial; font-size: 16px; font-weight: bold;"></div><div></div></div></div>
```

#### View Code
```
				$spreadlines = Lava::DataTable();
				$spreadlines->addDateTimeColumn('Timestamp')
							->addNumberColumn('Spread')
							->addRoleColumn('string', 'tooltip');
				$spreads = collect([Carbon::now()]);		
				$spreads->each(function($l) use($spreadlines) {
					$spreadlines->addRow([$l, -4.5, 'TODO:']);
				});			
				$period = new Period( new \DateTime('2018-01-21 11:00:00'), new \DateTime('2018-01-21 14:00:00'));
				$hTicks = [];
				foreach ($period->getDatePeriod('1 HOUR') as $immutable) {	
					$datetime = new \DateTime($immutable->format(\DateTime::ATOM));
					$hTicks[] = [ 'v' => $datetime ];				
                                }
								
				$linechart = Lava::LineChart('Spread', $spreadlines,
					[
						'title' => 'Spread Graph',						
						'height' =>  800,
						'width' => 1200,	
						'vAxis'  => [
							'textStyle' => ['color' => '#666'],	
							'ticks' => [ ['v' => -4.0, 'f' => 'TT-4.0'], [ 'v' => -4.05, 'f' => '-115'], [ 'v' => -4.1, 'f' => '-120'], [ 'v' => -4.15, 'f' => '-125'], [ 'v' => -4.2, 'f' => '-130'], [ 'v' => -4.25, 'f' => '+115'], [ 'v' => -4.3, 'f' => '+110'],[ 'v' => -4.35, 'f' => '+105'], [ 'v' => -4.4, 'f' => '+100'], [ 'v' => -4.45, 'f' => '-105'], [ 'v' => -4.5, 'f' => 'TT-4.5'], [ 'v' => -4.55, 'f' => '-115'], [ 'v' => -4.6, 'f' => '-120'], [ 'v' => -4.65, 'f' => '-125'], [ 'v' => -4.7, 'f' => '-130'], [ 'v' => -4.75, 'f' => '+115'], [ 'v' => -4.8, 'f' => '+110'],[ 'v' => -4.85, 'f' => '+105'], [ 'v' => -4.9, 'f' => '+100'], [ 'v' => -4.95, 'f' => '-105'], [ 'v' => -5.0, 'f' => 'TT-5.0']],
							'textStyle' => ['fontSize' => 10],
						],
						'hAxis' => [							
							'ticks' => $hTicks
						],	
						'events' => [
							'ready' => 'chartReady'
						],
					]
				);
			}

```

**Comment by jmichaelterenin** [comment] 2018-01-21 12:30
Is it because I'm supposed to be using Lava::jsDate or Lava::jsDateTime? I found jsDate referenced in a related issue, but no reference of it in the src directory.

**Comment by kevinkhill** [comment] 2018-01-21 16:45
First things first; could you please try your code with the most recent version of the library?

**Comment by kevinkhill** [comment] 2018-01-21 16:59
Also, I did used to require creating `Lava::jsDate` but it was tedious so I gave it the axe in favor of `Carbon` doing the heavy lifting. 

There is still https://github.com/kevinkhill/lavacharts/blob/3.1/src/Support/JavascriptDate.php but it was intended for me to use while copying examples from Google to test my charts. It does extend Carbon and can be used if you wish. You can see that it's nothing more than a wrapper to mimic the syntax of Javascript's `new Date()`

**Comment by jmichaelterenin** [comment] 2018-01-21 19:20
Updated to latest&greatest (3.1.9), thanks for that oversight.

Would I access the wrapper in the same manner? Lava::JavascriptDate(). I am getting:

`'JavascriptDate' is not a valid Lavachart object.: line 135 of C:\xampp\htdocs\covers\vendor\khill\lavacharts\src\Lavacharts.php`

Any assistance would be greatly appreciated : )

**Comment by kevinkhill** [comment] 2018-01-21 19:40
I will take a look and see if I can get a sense of what is going on.

**Comment by kevinkhill** [comment] 2018-01-21 19:49
Are you using http://period.thephpleague.com/ ?

**Comment by jmichaelterenin** [comment] 2018-01-21 19:50
Yes, but I've double-checked that the class of the object being "arrayed" is DateTime.

**Comment by kevinkhill** [comment] 2018-01-21 19:54
I can't get past this portion, and I'm not sure how to mock it so I can test

```
$spreads = $matchup->lines->filter(function($l) {
    return ($l->wagertype_id == 2);
});
```

**Comment by jmichaelterenin** [comment] 2018-01-21 19:55
Just remove it, irrelevant. just create a collect([]) with dummy data.

**Comment by kevinkhill** [comment] 2018-01-21 19:58
Within `$spreads->each()` you are `$spreadlines->addRow()`

I guess what I am asking, is do you have a simple example of what data you are using for the table?

I just want to add some rows and try to get it working.

I can't get past the PHP errors to see the Google errors

**Comment by jmichaelterenin** [comment] 2018-01-21 20:10
Updated the code to eliminate all the specific clutter related to my application.

**Comment by kevinkhill** [comment] 2018-01-21 20:23
OK! Now we're getting somewhere....

I can see that the `ticks` (since they are now `DateTime` objects are getting serialized down to `{"date":"2018-01-21 13:00:00.000000","timezone_type":1,"timezone":"-05:00"}`

since the error is `a.getTime is not a function` we can deduce that `a` must be a javascript `Date` object

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime

Therefore, we must get the ticks to be able to be serialized into `Date`s

**Comment by jmichaelterenin** [comment] 2018-01-21 20:26
Would that be a change inside or outside your package?

**Comment by kevinkhill** [comment] 2018-01-21 20:28
I will keep digging....

When the `DataTable` is serialized, we get the expected `new Date(2018,0,21,15,20,12)` output since `DateCells` [have the proper logic to serialize](https://github.com/kevinkhill/lavacharts/blob/3.1/src/DataTables/Cells/DateCell.php#L99-L119)

I think I need to get this same functionality into the parsing of the options.

**Comment by jmichaelterenin** [comment] 2018-01-21 21:44
I found this: https://groups.google.com/forum/#!topic/google-visualization-api/_-I98BPqeyM
Seems like it would be helpful to resolving my issue, but not sure how ...

**Comment by kevinkhill** [comment] 2018-01-21 21:49
I didn't know that in Javascript you could have the string date without
'new'

Hmmm.... Could you try assigning your ticks as strings? Following that same
format?

**Comment by jmichaelterenin** [comment] 2018-01-21 22:00
Do you mean this ?
`$hTicks[] = [ 'v' => $datetime->format('y,M,d,H'), 'f' => 'TODO:' ];`
Made no difference ...

**Comment by jmichaelterenin** [comment] 2018-01-21 22:31
Looks like I might have to convert the DateTime column to a Number column, unless you discover anything that helps resolves this. Thanks for your help thus far and anything you can do upcoming.

**Comment by kevinkhill** [comment] 2018-01-21 22:36
I had to take a break from my laptop, but I will try again later.

**Comment by jmichaelterenin** [comment] 2018-01-22 00:10
I'm having an issue getting hAxis ticks to work at all. No errors, they just don't display. I've got the DateTime converted to Number without any problems. Line chart displays fine. Wishing you had an example using hAxis ticks. Let me know if I should create another issue or not for your assistance on this.

: (

**Comment by kevinkhill** [comment] 2018-01-22 00:16
You can go ahead and make a hAxis ticks specific issue of you'd like.

On Jan 21, 2018 4:10 PM, "jmichaelterenin" <notifications@github.com> wrote:

I'm having an issue getting hAxis ticks to work at all. No errors, they
just don't display. I've got the DateTime converted to Number without any
problems. Line chart displays fine. Wishing you had an example using hAxis
ticks. Let me know if I should create another issue or not for your
assistance on this.

: (

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kevinkhill/lavacharts/issues/230#issuecomment-359294673>,
or mute the thread

**Comment by jmichaelterenin** [comment] 2018-01-22 03:52
Unfortunately, this error was not resolved by this fix: https://github.com/kevinkhill/lavacharts/issues/231

**Comment by kevinkhill** [comment] 2018-01-23 03:23
I have made some progress!

So, I [made a small class](https://github.com/kevinkhill/lavacharts/blob/dates/src/Support/Date.php) that uses a [DateableTrait](https://github.com/kevinkhill/lavacharts/blob/dates/src/Support/Traits/DateableTrait.php) which I borrowed from `DateCell` so that a `DateTime` instance can be serialized down to a javascript `Date`

You will need to wrap your hTicks DateTimes's in `Lava::Date()`

So in your code that you gave me...
```
foreach ($period->getDatePeriod('1 HOUR') as $immutable) {
    $datetime = new \DateTime($immutable->format(\DateTime::ATOM));
    $hTicks[] = [ 'v' => $datetime ];
}
```

try this instead...
```
foreach ($period->getDatePeriod('1 HOUR') as $immutable) {
    $datetime = new \DateTime($immutable->format(\DateTime::ATOM));
    $hTicks[] = [ 'v' => Lava::Date($datetime) ];
}
```

**Comment by kevinkhill** [comment] 2018-01-23 03:24
I am not certain what you are trying to chart out, but at least the error is gone and something displays.

Let me know if this works for you or if we need more tweaking. :+1:

**Comment by jmichaelterenin** [comment] 2018-01-23 03:31
Nice, thank you. Appreciate the package and your fantastic work. I've more forward with displaying time stamps as numbers, but I'm sure there are many others out there who welcome the fix and can put this package fix to good use.

**Comment by kevinkhill** [comment] 2018-01-23 03:56
So your hAxis ticks are just numbers? What is the difference / benefit
between datetimes and numbers?

I guess I still don't know what you are even charting 🤣

**Comment by jmichaelterenin** [comment] 2018-01-23 04:02
My horizontal axis are time stamps, I just told u that. The benefit would be to keep them as time stamps, but I moved on to converting the time stamp to a number. It's done. Maybe I'll switch back, I'll let you know if i do. Thanks!

**Comment by kevinkhill** [comment] 2018-01-23 04:15
Haha, no worries. It was a fun problem to solve. 

What I meant earlier was I didn't know what the whole chart was, not just the hAxis. Like it's purpose, because I couldn't think of how changing dates to numbers would work.

But I guess it's all numbers anyways!

Should we close this issue?

**Closed** 2018-01-25 02:17 UTC
