### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by TheTechnoMan** [kevinkhill/lavacharts#37] opened 2015-04-11 01:51 UTC
Hey,

there are some things for which I could not see a solution in the docs, please correct me if i missed something. I think that those things might be useful therefore I will write them down and you can decide what you think about them and maybe implement them in future version.

1) [DONE] Is there a way to check if the requested chart is available, to avoid an exception when trying to display a non existing chart? That should not be the case, but it would be more convenient to display something like "Graph currently unavailable" instead of having to deal with possible exceptions if something goes wrong.

2) [DONE] Is there a way to load/reload an chart over AJAX? For example when the user presses a button? 

3) [ALREADY IMPLEMENTED] Currently the JavaScript code is placed right where the chart should be displayed. Is this required, or would it be possible to place it at a custom location? I wanted to show an loading overlay until the chart has been rendered, sadly now the JS code for the chart(s) is executed way before the code for the overlay.

4) Is there a way to define a path where the required assets are stored locally? Currently it loads them from Google, which is not that great if you want to do performance optimizations.

Those are my ideas/concerns/questions that came up while working with the charts. Maybe there are some more in the future. Besides that, an amazing product. Really happy to found something like that.

Best regards,
Michael

**Comment by kevinkhill** [comment] 2015-04-11 02:03
1) Should be easy to do. Added to my TODOs

2) I'll have to think about this a bit, but it should be doable

3) Where ever you place the render() method or @linechart for example, is where the javascript code will fall, so it doesn't have to be in the middle of the page. You should be able to place that in the <head> or as the last line before the </body> and the chart will render into the specified div with the id="chartRendersHere" or whatever.

4) Right now, no, because I figured that people would want the most up-to-date version of the jsapi. Also, I seem to usually get a response in <100ms, but I could see how caching or bundling could come into play to eliminate an extra request.

**Comment by kyranb** [comment] 2015-04-11 16:37
+1 for ajax loading. This package is amazing, however for my use case, it's not really suitable to reload the entire page to change the data rendered.

If ajax was to be implemented, what do you think would be the best way to do so?

**Comment by kevinkhill** [comment] 2015-04-11 16:47
I was thinking... Maybe add a method onto the lava javascript object, like ```lava.reload('ChartType', 'ChartTitle', 'urlToNewDataTable')``` that would call with AJAX a server method that returns a new/updated DataTable for the specified chart.
Or...
```
lava.fetch('ChartType', 'ChartLabel', function() {
    // jQuery, or backbone or whatever you want
    // to fetch a new DataTable

    return dataTable;
});
```
So you could make your own AJAX call however you wanted, to get a new DataTable.

Thoughts?

**Comment by TheTechnoMan** [comment] 2015-04-11 16:53
Not sure how exactly this would work but it should be possible to make it so that there is no chart upon site loading and the chart(s) get loaded over AJAX when the site is ready. That is what I would love.

**Comment by kevinkhill** [comment] 2015-04-11 16:55
So you would want the charts to be LOADED on a button press/ajax, not RE-loaded?

**Comment by TheTechnoMan** [comment] 2015-04-11 17:39
I think that should be up to the user of your package, but I personally would love that. I would then be able to use lazy load to get the charts upon side load via AJAX and also could refresh them in the same way. Damn that would be amazing *_*

**Comment by kyranb** [comment] 2015-04-11 17:54
Yes, I would like the ability to RELOAD them(with new data) over ajax. 

@kevinkhill I think there are two ways this could be done. 

1. To keep things simple, LavaCharts could provide a method to 'render' a json DataTable. This has the added benefit of removing any restrictions on how the charts are implemented client side.

2. As you have said, with a javascript function that calls chart previously rendered.

**Comment by kevinkhill** [comment] 2015-04-14 02:12
Feature 1 added with version 2.4.2

**Comment by TheTechnoMan** [comment] 2015-04-14 02:23
Oh great, Would you mind giving an example on how to check inside blade, for example when I currently use `@areachart('registrations', 'registrations_div')`

Thanks!

**Comment by kevinkhill** [comment] 2015-04-14 02:30
You should be able to use the Facade within an @if block
```
@if (Lava::exists('AreaChart', 'registrations'))
    @areachart('registrations', 'registrations_div')
@endif
```

**Comment by TheTechnoMan** [comment] 2015-04-14 02:43
AH okay, I had it all lowercase. Thank you :)

**Comment by kevinkhill** [comment] 2015-04-15 01:49
Coming soon, to a Lavacharts near you...

[Ajax Loading!](http://i.imgur.com/lXjggun.gifv)

I need to polish it up a bit, and decide on the API for how it works, but the guts of it work!

So far, it looks like this:
```
<script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
<script type="text/javascript">
  $(function() {
    $('#ajax').click(function() {
      $.getJSON('http://localhost:8000/getDataTableJson', function (dataTableJson) {
         lava.reload('Votes', dataTableJson);
      });
    });
  });
</script>
```

I added ```lava.reload()``` to the lava javascript object, which accepts dataTableJson. Everything server side will be the same, you will just create a route that will return the JSON datatable. Inside the reload() method, a ```new google.visualization.DataTable``` is created and then the draw function of the chart is called again to reload the data.

**Comment by kyranb** [comment] 2015-04-16 16:16
@kevinkhill Thanks! This package is 10 times more useful now with that getDataTableJson method. 

I'd love to try out the the ajax feature but the reload method is missing. Would you be able to push it to the ajax branch?

**Comment by kevinkhill** [comment] 2015-04-16 16:45
I changed it to lava.loadData, reload didn't fit to me because a first load
wouldn't be a reload

**Comment by TheTechnoMan** [comment] 2015-04-18 00:20
Awesome news. I am a bit confused about how the integration. Currently I create the datatable and then set the options on it. How to do that now with AJAX? 

Thanks

**Comment by kevinkhill** [comment] 2015-04-18 00:35
So right now, (I know it's a bit hacky), but this is how I have it working

# Routes
```
Route::get('ajaxTest', function()
{

    $temperatures1 = Lava::DataTable();
    $temperatures2 = Lava::DataTable();

    $temperatures1->addDateColumn('Date')
                  ->addNumberColumn('Max Temp')
                  ->addNumberColumn('Mean Temp')
                  ->addNumberColumn('Min Temp');

    $temperatures2->addDateColumn('Date')
                  ->addNumberColumn('Max Temp')
                  ->addNumberColumn('Mean Temp')
                  ->addNumberColumn('Min Temp');

    Lava::LineChart('Chart1')
        ->dataTable($temperatures1)
        ->title('Weather in October');

    Lava::LineChart('Chart2')
        ->dataTable($temperatures2)
        ->title('Weather in November');

    return View::make('ajaxTest');
});

Route::get('getDataTableJson', function()
{
    $tz = 'America/Los_Angeles';

    $temperatures1 = Lava::DataTable($tz);
    $temperatures2 = Lava::DataTable($tz);

    $temperatures1->addDateColumn('Date')
                  ->addNumberColumn('Max Temp')
                  ->addNumberColumn('Mean Temp')
                  ->addNumberColumn('Min Temp');

    foreach(range(1, 30) as $day) {
        $temperatures1->addRow(array('2014-10-'.$day, rand(50,90), rand(50,90), rand(50,90)));
    }

    $temperatures2->addDateColumn('Date')
                  ->addNumberColumn('Max Temp')
                  ->addNumberColumn('Mean Temp')
                  ->addNumberColumn('Min Temp');

    foreach(range(1, 30) as $day) {
        $temperatures2->addRow(array('2014-11-'.$day, rand(50,90), rand(50,90), rand(50,90)));
    }

    return $temperatures1->toJson();
    //return $linechart->getDataTableJson();
});
```

# View
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charschartset="UTF-8">
    <title>Lavabench</title>
  </head>

  <body>
    <button id="ajax">AJAX!</button>
    <br />
    <div id="chart1" style="width:50%"></div>
    <br />
    <div id="chart2" style="width:50%"></div>

    @linechart('Chart1', 'chart1')
    @linechart('Chart2', 'chart2')

    <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
    <script type="text/javascript">
      $(function() {
        $('#ajax').click(function() {
          console.log('requesting...');
          $.getJSON('http://localhost:8000/getDataTableJson', function (dataTableJson) {
            console.log(dataTableJson);
            console.log('...complete');

            console.log('rendering...');
            lava.loadData('Chart1', dataTableJson, function (chart) {
              console.log('...complete');
            });
          });
        });
      });
    </script>
  </body>
</html>
```

**Comment by TheTechnoMan** [comment] 2015-04-18 00:44
Oh okay. But this requires to render the chart at least once before rendering it (again) with AJAX?

**Comment by kevinkhill** [comment] 2015-04-18 00:47
It initially loads the frame of the chart with no data and then the ajax
will fetch data (as it changes I assume)

**Comment by TheTechnoMan** [comment] 2015-04-18 00:55
Ah I see. For some reasons it does not reload it for me. Is it normal that in FireBug the response looks like that:
http://i.epvpimg.com/Gmxke.png
?

**Comment by kevinkhill** [comment] 2015-04-18 00:59
Didn't mean to close this, accidental click. XD

Anyways, it Chrome's console, I see it coming through as valid json

[Imgur](http://i.imgur.com/4IwTegN.png)

**Comment by TheTechnoMan** [comment] 2015-04-18 01:04
A console dump looks like that for me:
http://i.epvpimg.com/64EJb.png

It does show the correct content but it does not show up as JSON. Also the error does look good :(

**Comment by TheTechnoMan** [comment] 2015-04-18 01:25
Okay found it. But there seems to be a bug as well. Try to resize your window after reloading the chart by using AJAX. It will reset back to the original (empty) one.

**Comment by kevinkhill** [comment] 2015-04-18 02:03
I just installed firefox with firebug to see what I get and my output looks like json, and the charts render... Hmmmm

[firefox + firebug] (http://i.imgur.com/bPeAfFa.png)

**Comment by kevinkhill** [comment] 2015-04-18 02:10
dammit, resize bug confirmed.... I think Its because In order to make the charts responsive, I had to attach the draw function to the window resize event. Instead of loading the data into the draw function, from the ajax call, I think I need to have it store it in the chart, THEN call the draw function....

right now, the draw function gets the new data
```
...
chart.draw(newDataTable, chart.options);
```

but the resize method just calls draw, so its using the original data (which there was none)
```
...
lava.charts[parts[0]][parts[1]].draw();
```

**Comment by TheTechnoMan** [comment] 2015-04-18 02:13
Yeah, that it what I thought as well. I never expected to find a bug in your product, glad that I made it lol

**Comment by kevinkhill** [comment] 2015-04-18 02:15
I'm not perfect, haha, and we're bound to find bugs while this is still a work in progress. Thank you for helping test this out. I would much rather find bugs in development instead of pushing bugfixes after the fact. I'm looking into the lava.js file to see how to work around this.

**Comment by TheTechnoMan** [comment] 2015-04-18 02:19
Haha :P Alright thanks.

I still wonder why it does not get into the function for me to display the "complete". DO you see anything wrong in my code:

```
        $(function() {
            $('#button_registrations').click(function() {
                $('#registrations_div_top').loadingOverlay({
                    "startShowing": true,
                    "hideOnWindowLoad": false
                });

                $.getJSON('{{ route('get.graphs.fetch', 'registrations,loginAttempts') }}', function (dataTableJson) {
                    console.log('rendering...');
                    lava.loadData('registrations', dataTableJson.registrations, function (chart) {
                        console.log('...complete');
                        //var $el = $('#registrations_div_top');
                        //$el.trigger('loading-overlay:hide');
                    });

                    lava.loadData('loginAttempts', dataTableJson.loginAttempts, function (chart) {
                        console.log('...complete');
                    });
                });
            });
        });
```

Thank you! Damn, already 4AM again. Time is passing by too fast :(

**Comment by kevinkhill** [comment] 2015-04-18 02:23
Probably because in my lava.js file I never actually called the callback.... whoops! I just added it if you want to pull from the ajax branch.

**Comment by TheTechnoMan** [comment] 2015-04-18 02:40
Thanks!

**Comment by TheTechnoMan** [comment] 2015-04-18 03:13
Looks like I found another issue, just noticed it. The styling options work fine on the empty (pre-rendered) chart but do not apply on the AJAX ones. So basically after rendering it again, the graphs have the default styling.

**Comment by kevinkhill** [comment] 2015-04-18 03:19
I just fixed the redraw on resize issue, let me look into that

**Comment by TheTechnoMan** [comment] 2015-04-18 03:20
Great to hear. Hope you can figure that one out as well :)

**Comment by kevinkhill** [comment] 2015-04-18 03:22
It looks like my last commit fixed the customization issue as well :) Accidental bugfix

**Comment by TheTechnoMan** [comment] 2015-04-18 03:39
Yep it did. Thank you very much. The last thing on my personal wishlist is the thing with the locally stored files. Any chance that you implement that? I mean you could make it optional, so create a config for it where you can enable/disable it and maybe set the path to the files (if you don't have an other/better idea to do that).

Really need to go to bad now, 6AM here. Thanks again!

**Comment by kevinkhill** [comment] 2015-04-18 03:41
I'll look into it to see if that would be easy to implement

**Comment by TheTechnoMan** [comment] 2015-04-18 03:42
Alright, thank you very much :)

Have a good night later on!

**Comment by TheTechnoMan** [comment] 2015-04-18 03:52
Now that I think about it, an option to just turn off the automatically including would be perfectly fine. Thats basically all.

Am 18. April 2015 05:41:19 MESZ, schrieb Kevin Hill <notifications@github.com>:

I'll look into it to see if that would be easy to implement

—
Reply to this email directly or view it on GitHub<https://github.com/kevinkhill/lavacharts/issues/37#issuecomment-94122467>.

________________________________

Höhere Technische Bundeslehr- und Versuchsanstalt Spengergasse

HTBLuVA
Spengergasse 20
1050 Wien
Tel.: +43 (0)1 54615 0
Fax: +43 (0)1 546 15-139

www.spengergasse.at

Dieses E-Mail ist vertraulich und kann rechtlich geschützte Informationen beinhalten. Wenn Sie nicht der beabsichtigte Adressat sind, sind Sie nicht autorisiert, diese Nachricht zu lesen, zu drucken, zu speichern, zu verarbeiten oder weiterzugeben. Wenn sie diese Nachricht irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie dieses E-Mail die angeschlossenen Dateien sowie alle Ausdrucke und Kopien. Jegliche Nutzung, Verbreitung, Vervielfältigung oder Offenlegung von einer anderen Person als dem beabsichtigten Empfänger ist strengstens verboten, und kann rechtliche Konsequenzen nach sich ziehen.
This e-mail is confidential and may also contain privileged information. If you are not the intended recipient, you are not authorised to read, print, save, process or disclose this message. If you have received this message by mistake, please inform the sender immediately and delete this e-mail, its attachments and any copies. Any use, distribution, reproduction or disclosure by any person other than the intended recipient is strictly prohibited and the person responsible may incur penalties. Thank you!

**Comment by kevinkhill** [comment] 2015-04-19 20:47
I am still a little curious why you would want to include the jsapi manually. Is it that you just want to place it in a specific place in the view? If so, you can already do that with the jsapi method from the lavacharts object.

If it was to save a request to google, then I don't get it because once loaded, the jsapi makes requests to google anyways to get the specific assets for the charts you are rendering, so what is the harm with one more to get the jsapi?

**Comment by TheTechnoMan** [comment] 2015-04-21 16:16
Well, there are actually multiple reasons for example minifying. There is no way to host all the required assets locally?

**Comment by kevinkhill** [comment] 2015-04-21 16:22
I'm not sure? I suppose you could capture each request, download it manually, then add it to your asset build? You would then be missing out on possible newer versions or fixes that would have been pulled in manually. Make a test page, or just go to one of your charts and watch the console as a it renders. You will see that more scripts and css are pulled in.

For I could still enable an option to not drop in the jsapi, but then you would still face the jsapi making its own calls, which is out of the scope of this project for me to try and mitigate.

**Comment by TheTechnoMan** [comment] 2015-04-22 15:43
Okay, I will try that, even though I have the feeling that google will ignore the included assets and still pull them in anyways. It looks like that the issue with the callback is back since you did an update? It does no longer get called.

**Comment by kevinkhill** [comment] 2015-04-25 06:45
I did a little more cleanup, as far as I can tell, the callbacks work now.

**Comment by kevinkhill** [comment] 2015-04-25 07:28
Just pushed version 2.5, which includes ajax loading. Hooray!

**Comment by kyranb** [comment] 2015-04-25 13:38
Sorry to open this back up, but after updating, I'm getting chart not found error's.
![screenshot 2015-04-25 23 35 29](https://cloud.githubusercontent.com/assets/5426926/7333087/feb2ec1e-eba3-11e4-8fe1-a790d33f3705.png)

I'm sure that there's something simple that was changed in the last few commits that is causing this, but I can't figure out what it is. Any ideas?

**Comment by TheTechnoMan** [comment] 2015-04-25 15:50
I updated to 2.5 as well and sadly also have issues. The reloading does not work (it sends an ajax requests though) and the callback does not work either.

**Comment by TheTechnoMan** [comment] 2015-04-25 16:13
Its working fine for me. Ty!

**Comment by kevinkhill** [comment] 2015-04-25 23:35
So it looks like I should write some tests for the lava.js object. It seems to work on my end, but that's a bad excuse. I will start reading up on how to write unit tests for javascript and make sure that the lava.js object behaves how I expect it to.

**Comment by kevinkhill** [comment] 2015-04-26 23:02
@kyranb, it turns out that my loop, searching for the charts was finding them, and also throwing the error. I am trying to refactor and create tests to prevent this sort of mixup in the future. I don't know very much about gulp, node, jasmine, phantomjs... But I am trying to figure it out. You can give the new js-tests branch a try, might fix your issues.

**Comment by kyranb** [comment] 2015-04-27 18:34
@kevinkhill Just tested the js-tests branch, everything is working perfectly now :+1: 

And yeah, the javascript world is a little crazy - which happens to be one of the reasons why I love this package so much. Once again, huge thanks for this functionality and all the other work you've put into Lavacharts Kevin!

**Comment by kevinkhill** [comment] 2015-04-28 20:15
Just pushed 2.5.1, with fixes from the js-tests branch merged in. I also figured out karma and having travis run my js tests :) This should help keep things running smoothly in the future.

Finally closing this!

**Closed by kevinkhill** 2015-04-28 20:15 UTC
Labels: enhancement
