### ISSUE TITLE
[V3, Laravel] Multiple charts on the same page

### ISSUE THREAD

**Issue by KoenLav** [kevinkhill/lavacharts#141] opened 2016-05-15 10:43 UTC
When multiple charts are rendered on the same page the lava.js file is included for the first graph, causing lava.run to be called right after the first graph.

Lava.run in turn fires the jsapi:ready event to which all individual graphs are listening, but in our specific implementation the Javascript for the last few graphs (5 out of 15) is not yet executed. As a result they are not (yet) listening for the event and when they do start listening the event will have already fired.

Proposed solutions:
- either call lava.run after the last graph (this is probably impossible);
- provide the option to call lava.run manually (which is what we are currently doing);
- make modifications to the event emitter which will cause it to also run listeners attached to an event which has already fired (probably the best resolution, but requires a little rework);
- modify the code where the graph listens for the event to either listen for the event or check a variable which is set to true after the event (lava.jsapiReady = true).

**Comment by kevinkhill** [comment] 2016-05-22 17:54
I believe I have this issue solved in the master branch. I switched from events to promises to have better control of the flow of execution. If you are feeling adventurous, I believe the master branch has working code, to test against, and will eventually be merged into the 3.0 branch. I have no idea of a timeline, since my real job and life are demanding at the moment, so, no promises on when I can work more.

**Comment by KoenLav** [comment] 2016-05-22 20:36
For now I managed to satisfy our requirements, so will keep my own modified code.

Just wanted to share my findings with you ;)

**Comment by kevinkhill** [comment] 2016-05-22 23:01
I'm glad you were able to solve your problem, and thanks for your insight. I am not the best Javascript developer, but I like how promises work over events

**Comment by bparsons** [comment] 2016-06-28 21:37
Hi - I am testing this from master but running into a problem where Google is not wanting google.charts.load to be called more than once: loader.js:146 Uncaught Error: google.charts.load() cannot be called more than once with version 45 or earlier.

**Comment by kakaroto84** [comment] 2016-11-24 20:00
If have the same issue with the last version. 
But i make some test and i think find the solution.

\vendor\khill\lavacharts\src\Javascript\ChartFactory.php

The problem is that cant load more charts. I fixed that doing lava to be ready again. So in 

`function getTemplate: 143`

I add this lines

```
lava.attachRedrawHandler(window);
lava.run(window);
```

That's work for me.

**Comment by vanessasoutoc** [comment] 2017-04-10 20:27
I have this problem!!
Please, gisthub for help me

**Comment by kevinkhill** [comment] 2017-04-12 00:41
I believe this issue has been solved in v3.1 with the refactored lava.js module. Please upgrade a see if you issues are resolved. I'm closing this issue for now. Please open a new issue if you still need help.

**Closed by kevinkhill** 2017-04-12 00:41 UTC
Labels: bug

**Comment by huuloc4193** [comment] 2018-09-14 04:34
@kevinkhill could you check again.
I still have same problem w/ latest version.

**Comment by kyranb** [comment] 2019-08-11 03:18
Thanks so much! Just ran into the same issue!!

Any ideas on how to still set a font without running into this issue?
