### ISSUE TITLE
Chart Height Issues when Target DIV has Text

### ISSUE THREAD

**Issue by SendDerek** [kevinkhill/lavacharts#71] opened 2015-10-29 19:58 UTC
When the target DIV has text, the chart renders with a height of the text height.  My goal is to have a spinning font-awesome icon to indicate that the chart is loading.  So, my HTML looks like:

    <div id="perf_div"><i class="fa fa-spinner fa-pulse"></i></div>
    {!! \Lava::render('LineChart', 'Stocks', 'perf_div') !!}

When I do this, I would expect the chart to look the same as it does with this HTML:

    <div id="perf_div"></div>
    {!! \Lava::render('LineChart', 'Stocks', 'perf_div') !!}

Instead, the chart takes on the height of the DIV content to look like this:

    <div id="perf_div">
        <div style="position: relative;">
            <div dir="ltr" style="position: relative; width: 935px; height: **19px;**">
            ...

![screen shot 2015-10-29 at 1 42 10 pm](https://cloud.githubusercontent.com/assets/469263/10829993/f0890312-7e42-11e5-9a3c-f86baa5ecb19.png)

I would expect it to look the same as this:

    <div id="perf_div">
        <div style="position: relative;">
            <div dir="ltr" style="position: relative; width: 935px; height: **200px;**">

![screen shot 2015-10-29 at 1 43 13 pm](https://cloud.githubusercontent.com/assets/469263/10830021/093e85f8-7e43-11e5-9e10-c11376334ace.png)

I get the same squished result with plain text as well:

    <div id="perf_div">Test</div>
    {!! \Lava::render('LineChart', 'Stocks', 'perf_div') !!}

Passing divDimensions into Lava::render() doesn't help since it only affects the div "perf_div" and not the inner divs.  I'm afraid my javascript debugging skills aren't very great.  I'm hoping you can help me with this issue.

**Comment by kevinkhill** [comment] 2015-10-29 20:29
I will take a look when I get a chance, as this is an interesting bug you have found

**Comment by kevinkhill** [comment] 2015-11-12 17:43
It's quite possible that this is an issue with Google Charts and not on my end. I was able to reproduce the skinny chart by using your spinner example, but haven't really dug into the cause yet

**Comment by kevinkhill** [comment] 2015-11-22 16:09
After a couple tests, it looks like you will just need to add the height you want as an option when configuring the chart in php. From what I can tell, if the div is not empty, then the google chart will just adopt the height of the div. Applying the height you want will solve this.

just add a line like ```'height' => 200,``` to your config array and it should resolve the squashed chart issue.

**Comment by SendDerek** [comment] 2015-11-22 18:26
I attempted that as well, but the width attribute was required to be set as well.  So, while setting the height was okay, I couldn't set the width to be something sane for responsive design, like 100%.  It had to be an integer.

**Comment by kevinkhill** [comment] 2015-11-22 18:29
Hmm, so my test might have been too simple. (it was just one div with the FA spinner) I'll take another look later today

**Comment by kevinkhill** [comment] 2015-11-22 18:32
Are you using bootstrap or something? If I'm trying to debug your specific issue, it might help me make a more accurate test page. Could you maybe gist me the html you are using? Or should I just grab a responsive template from somewhere.

**Comment by SendDerek** [comment] 2015-11-22 19:56
Yeah, that'd work.  Just grab an example bootstrap template that uses grid layout with panels.  Something like this:

    <div class="row">
        <div class="col-lg-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-line-chart fa-fw"></i> Chart Example 1
                </div>
                <div class="panel-body">
                    <div id="chart1"><i class="fa fa-spinner fa-pulse"></i></div>
                </div>
            </div>
        </div>
    </div>

Then, of course, we do a `render()` with the 'height' option passed in:

        {!! \Lava::render($chart->getType(), (string)$chart->getLabel(), (string)$chart->getLabel(), ['height' => 500], true ) !!}

And you'll be met with an error:

    Invalid div dimensions, array('height' => (int), 'width' => (int))

So, then you can set the width, but it's forced to that width.  Resizing the window simply causes the graph to overflow outside the panel div.  It'd be nice if we could specify either width or height without needing to set both.

I think I see where to do this... I'll be back with a pull request shortly.

**Comment by SendDerek** [comment] 2015-11-22 20:09
That's a nasty looking pull request.  I obviously did something wrong there or didn't pull before submitting.  I'm too lazy to fix it though!  At any rate, the patch is here:
https://github.com/SendDerek/lavacharts/commit/24e8167cba2aa3360771588536ae7dac08dadae5

Let me know if I should re-submit the pull request or something.

**Comment by kevinkhill** [comment] 2015-11-23 00:12
Oh I wish I could have explained more clearly the first time, before you dug into the code. I could have saved you some time... 

I meant in the php side of configuring the chart, add the height option to the initial configuration array. That will transfer into the Google chart api for a rendered height.

You were trying to use my old, clunky way of generating the div. I'm sorry I didn't explain that better in the first place!

**Comment by kevinkhill** [comment] 2015-11-23 01:30
Ok, so here is the original reason for even including the div generator method:

I noticed in the docs for [Timelines](https://developers.google.com/chart/interactive/docs/gallery/timeline#a-simple-example) that the div needed a set height, and I figured I could make that easier by including a way to generate specific height divs. I believe that Timelines are the only ones that need the div to have a predefined height and all others can use the height option when building the chart.

In all honesty, the whole div generation method could probably be ripped out, but I don't know if people actually use it or not.

**Comment by SendDerek** [comment] 2015-11-24 05:16
Ah, thank you for the explaination.  I always wondered about the mysterious fifth parameter!

I'd be all for keeping the render method as simple as possible (even removing the chart type parameter requirement like we've discussed in https://github.com/kevinkhill/lavacharts/issues/72).  A deprecated flag / notice would make sense for now and result in better user experience than just ripping it out.  I'm sure folks will want to be able to upgrade from 2.x to 3.x easily.

**Comment by kevinkhill** [comment] 2015-11-24 07:03
If you want to clean up your pull request for the div method, I'd be happy to merge it, but for now, I'm just going to close this issue.

**Closed by kevinkhill** 2015-11-24 07:03 UTC
Labels: bug
