### ISSUE TITLE
Lavachart to image

### ISSUE THREAD

**Issue by emmanuelLS** [kevinkhill/lavacharts#112] opened 2016-03-04 08:23 UTC
I am using version 3.0 

Is it possible to export the chart as image file? 
I tried your solution but the getImageURI() is not working. Can you please give me a working example on this? 

Thanks

**Comment by kevinkhill** [comment] 2016-03-04 12:26
I have been working on a method for enabling this in a much more simple way than my current example, but for now, can you tell me what version you are using?

**Comment by kevinkhill** [comment] 2016-03-04 12:32
Your issue prompted me to look at the wiki pages, and it wasn't even a valid example... Oops!

I updated the one, and added another, so check there first to see if it is a simple fix.

**Comment by emmanuelLS** [comment] 2016-03-04 12:37
Hi ,, I'm using 3.0,. 
I was trying to display the chart on a PDF but I cant get it work. 
is it working on lower version?

**Comment by kevinkhill** [comment] 2016-03-04 12:44
I just tested the example from my wiki and it works? I'm seeing the encoded png in the console. You will still need to then take that, and drop it into and image tag

```<img src="URI_HERE" />```

using javascript

**Comment by emmanuelLS** [comment] 2016-03-04 12:58
I still have error 

`Uncaught TypeError: chart.getImageURI is not a function`

So URI should be called using javascript? is it possible to store the image without prompt?

**Comment by kevinkhill** [comment] 2016-03-04 18:21
Could you share your code? I might be able to spot there error.

**Comment by emmanuelLS** [comment] 2016-03-08 08:26
Here is my code 

```
		$nurse_admin_to_doctor_ratio  = Lava::DataTable();							         
		$nurse_admin_to_doctor_ratio->addStringColumn('')
			    ->addNumberColumn('Nurse to Doctors Staff Ratio')
			    ->addNumberColumn('Administrator to Doctors Staff Ratio')
			    ->addRow(['Your Pratice', $nurse_to_doctor_ratio, $administrator_to_doctor_ratio])
			    ->addRow(['Benchmark Same Size Practice', 2, 20])
			    ->addRow(['Benchmark All', $nurse_to_doctor_ratio_benchmark_all, $administrator_to_doctor_ratio_benchmark_all]);

		Lava::ColumnChart('staffratio', $nurse_admin_to_doctor_ratio,[
				'titleTextStyle' => [
						'color' => '#eb6bb2c',
						'fontSize' => 10
				],
				 'legend' => [
			        'position' => 'top'
			    ],
			    'barGroupWidth' => "10%",
			     'events' => [
			        'ready' => 'getImageCallback'
			    ]
			  
			]);	
```


And here is how I call the script

<script type="text/javascript">
							    function getImageCallback (event, chart) {
							        console.log(chart.getImageURI());
							        // This will return in the form of "data:image/png;base64,iVBORw0KGgoAAAAUA..."
							    }


getImageCallback('ready', 'staffratio');
							</script>

**Comment by emmanuelLS** [comment] 2016-03-08 08:27
Im thinking of simply storing the chart on local storage after rendering. 

Is that possible?

**Comment by kevinkhill** [comment] 2016-03-08 12:50
I think you just need to remove this line:
```getImageCallback('ready', 'staffratio');```

The reason being, it is a callback that gets assigned to the ready event, within the chart drawing method. If you are curious, use the inspector to look at the chart code, and you will find that your callback is assigned with an event listener.

The error is coming from the fact that you passed a string to the callback, ```staffratio```

**Comment by kevinkhill** [comment] 2016-03-19 16:47
I haven't written all the docs for 3.1 yet, but if you want to use the dev-3.1 branch, creating image charts is simple. All you have to do is add ```'png' => true``` to the chart options and it will render in page as a static chart.

**Comment by emmanuelLS** [comment] 2016-04-26 04:00
Hi, 

I know this has been answered already, but I noticed that the chart.getImageURI is not working anymore, 

I tried to used console.log(chart.getImageURI()) and no output being displayed. 

This is my codes 

Controller

```
public function testLavaChart(){

		$population = Lava::DataTable();

		$population->addDateColumn('Year')
		           ->addNumberColumn('Number of People')
		           ->addRow(['2006', 623452])
		           ->addRow(['2007', 685034])
		           ->addRow(['2008', 716845])
		           ->addRow(['2009', 757254])
		           ->addRow(['2010', 778034])
		           ->addRow(['2011', 792353])
		           ->addRow(['2012', 839657])
		           ->addRow(['2013', 842367])
		           ->addRow(['2014', 873490]);

		Lava::AreaChart('Population', $population, [
		    'title' => 'Population Growth',
		    'legend' => [
		        'position' => 'in'
		    ],
		    'events' => [
		    		'ready' => 'getImageCallback'
		    ]
		]);
		return view('lavachart');
	}

```
View

```
<div id="pop_div"></div>
// With Lava class alias
<?= Lava::render('AreaChart', 'Population', 'pop_div') ?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script type="text/javascript">

    function getImageCallback (event, chart) {
        console.log(chart.getImageURI());
        // This will return in the form of "data:image/png;base64,iVBORw0KGgoAAAAUA..."
    }
</script>
```

**Comment by kevinkhill** [comment] 2016-04-26 04:10
I'm getting much closer to a big update for the 3.0 branch, but I will check and see if I broke the imageURI

**Comment by emmanuelLS** [comment] 2016-04-26 04:19
Oh please! this is really urgent. :(

**Comment by kevinkhill** [comment] 2016-04-26 14:48
I have working PNG charts if you want to try out the ```dev-3.0``` dependency over ```3.0.*``` Once I have finished testing and documentation, then a new tag will be released and you can continue to use the ```3.0.*```

Just add to your chart's options, ```[ 'png' => true ]``` and it should come out as a static image

**Comment by emmanuelLS** [comment] 2016-04-26 22:04
Nice, I have tested it already and it works. 

That's a cool feature, I hope you can release it soon. 
Right now, I will stick to 3.0.* since it is the latest release. 

Thanks,

**Closed** 2016-04-27 13:19 UTC
Labels: enhancement, question

**Comment by aparedesBB** [comment] 2019-02-28 18:42
Hey @emmanuelLS  , @kevinkhill  do you know if I can use

`'PNG' => true`

option to render the chart in a PDF?

**Comment by jacoboospina** [comment] 2019-11-08 11:39
Hello! I've used `'png' => true` to render the chart as image, If print it in blade I can see it printed as image, but if I try to render it in a pdf, it doesn't show anything... any ideas?
Thank you

**Comment by kevinkhill** [comment] 2019-11-08 12:15
Drawing the chart as an image technically draws it normally, then replaces
it with an image. If you are rendering the view to pdf server-side, then
the Javascript that Lavacharts uses never gets ran, and in turn, no charts.

Im sorry, but Google Charts was designed to run in browser, so if you are
going from blade to pdf, the Javascript will never be executed.

**Comment by jacoboospina** [comment] 2019-11-08 12:20
Thank you for the early reply... So there is any way to print the image/chart on a pdf using Lavachart?

**Comment by kevinkhill** [comment] 2019-11-08 12:59
There are ways, but very convoluted.
I've successfully used PhantomJs to automate the generation of charts as
images all on the server.

It feels like using a hammer on a screw though...

Google charts seems to be designed as a browser lib, not as a server-side
lib

**Comment by jacoboospina** [comment] 2019-11-08 13:06
Mmmm I see... Any other libs that I can use to make it work? I just need to create a chart and print it on pdf.. may be generating an image with the data? like a svg?

**Comment by kevinkhill** [comment] 2019-11-08 15:25
I'm not sure how your server is setup, but after a quick Google, this looks
interesting?

https://wkhtmltopdf.org/

Or use PhantomJs / NightmareJs / Chrome Headless to execute the Javascript

**Comment by jacoboospina** [comment] 2019-11-11 08:06
Thank you, I will try any of those...

**Comment by jacoboospina** [comment] 2019-11-11 12:31
I finally used pChart 2.0 to print the chart in a pdf.

**Comment by kevinkhill** [comment] 2019-11-11 12:53
Nice! They must be using GD or ImageMagick php extensions for all the
drawing. Good find
